server:
  address: localhost
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
<<<<<<< Updated upstream
    url: jdbc:mariadb://i8b301.p.ssafy.io:3306/bora?serverTimezone=UTC&characterEncoding=UTF-8
=======
    url: jdbc:mariadb://i8b301.p.ssafy.io/bora?serverTimezone=UTC&characterEncoding=UTF-8
>>>>>>> Stashed changes
    username: ssafy
    password: ssafy
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        globally_quoted_identifiers: true
#        format_sql: true

  cache: redis
  redis:
    host: localhost
    port: 6379
    password: b301

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
