spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 506dd048e8b6d28b22eaf5dce091b0df
            client-secret: Vt2tpawo77d5tEkgJGV9WjBolfMfBv1r
            redirect-uri: https://i8b301.p.ssafy.io/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            client-id: 6994198e0a1efb1a987463241de95a65
            client-secret: Jt9Ivb3sH4dktweIsB2RSA1wXL8fuDRE
            redirect-uri: https://i8b301.p.ssafy.io/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao


app:
  auth:
    jwt:
      secret-key: ASDHLKjWDUHASf676SJDfh623DAF8