server:
  address: localhost
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://i8b301.p.ssafy.io/bora?serverTimezone=UTC&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
  cache:
    type: redis
    redis:

  redis:
    host: localhost
    port: 6379
    password: b301
  profiles:
    include: oauth

cloud:
  aws:
    credentials:
      accessKey: AKIA4FYBPHWXAAKBP2MC
      secretKey: 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
    s3:
      bucket: woojin-test-bucket
      # dir: kwj
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
