server:
  address:
  port: 8080
  servlet:
    context-path: /api

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(w+v9nu+Ntv0+s9QUaiz4VgcGloO89gs0IVh+7m+THm3OuJjK6H6voJLoK2lcQWzmT6V/JfOoVNTieFMe3ZlrqnfWpguucxpUEn5ILLqbUIjry03hypQrmF3irwKlX7hC)
    username: ENC(IOvBivSpocQ38UJMe1yl9g==)
    password: ENC(09vfPMIkaeR8S2PSSSqPTA==)
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
  cache: redis
  redis:
    host: i8b301.p.ssafy.io
    port: 8379
    password: ENC(71dZ7p+B8r0mcHdbH4omRw==)
  profiles:
    include: oauth
  # swagger오류때문
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #jasypt 설정
cloud:
  aws:
    credentials:
      accessKey: ENC(O4x+LFHQgUPoFpJ6KiFLpPjNRt2O0/tzfN+xhdipSNY=)
      secretKey: ENC(cvepBrnVGu7YauXISaMoTZ3WLf8tjgpbG595TrTxWBRT6ptqEzG8gLZYK4IxMvNFAHv5h0+biYI=)
    s3:
      bucket: woojin-test-bucket
      # dir: kwj
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
